<?php

namespace Tests\Feature\Http\Controllers\Frontend\User;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Frontend\User\DashboardController
 */
class DashboardControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('frontend.user.dashboard'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Frontend\User\DashboardController::class,
            'index',
            \App\Http\Requests\Frontend\User\DashboardViewRequest::class
        );
    }

    // test cases...
}
