<?php

namespace Tests\Feature\Http\Controllers\Backend\Faqs;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Backend\Faqs\FaqsTableController
 */
class FaqsTableControllerTest extends TestCase
{
    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin.faqs.get'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function __invoke_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Faqs\FaqsTableController::class,
            '__invoke',
            \App\Http\Requests\Backend\Faqs\ManageFaqsRequest::class
        );
    }

    // test cases...
}
