<?php

namespace Tests\Feature\Http\Controllers\Backend\Faqs;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Backend\Faqs\FaqStatusController
 */
class FaqStatusControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.faqs.mark', ['faq' => $faq, 'status' => $status]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Faqs\FaqStatusController::class,
            'store',
            \App\Http\Requests\Backend\Faqs\EditFaqsRequest::class
        );
    }

    // test cases...
}
