<?php

namespace Tests\Feature\Http\Controllers\Backend\Access\User;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Backend\Access\User\UserStatusController
 */
class UserStatusControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function delete_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.access.user.delete-permanently', ['deletedUser' => $deletedUser]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Access\User\UserStatusController::class,
            'delete',
            \App\Http\Requests\Backend\Access\User\DeleteUserRequest::class
        );
    }

    /**
     * @test
     */
    public function get_deactivated_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.access.user.deactivated'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function getdeactivated_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Access\User\UserStatusController::class,
            'getDeactivated',
            \App\Http\Requests\Backend\Access\User\ManageDeactivatedRequest::class
        );
    }

    /**
     * @test
     */
    public function get_deleted_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.access.user.deleted'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function getdeleted_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Access\User\UserStatusController::class,
            'getDeleted',
            \App\Http\Requests\Backend\Access\User\ManageDeletedRequest::class
        );
    }

    /**
     * @test
     */
    public function mark_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.access.user.mark', ['user' => $user, 'status' => $status]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function mark_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Access\User\UserStatusController::class,
            'mark',
            \App\Http\Requests\Backend\Access\User\EditUserRequest::class
        );
    }

    /**
     * @test
     */
    public function restore_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.access.user.restore', ['deletedUser' => $deletedUser]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function restore_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Access\User\UserStatusController::class,
            'restore',
            \App\Http\Requests\Backend\Access\User\DeleteUserRequest::class
        );
    }

    // test cases...
}
