<?php

namespace Tests\Feature\Http\Controllers\Backend\Access\User;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Backend\Access\User\UserSessionController
 */
class UserSessionControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function clear_session_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin.access.user.clear-session', ['user' => $user]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function clearsession_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Backend\Access\User\UserSessionController::class,
            'clearSession',
            \App\Http\Requests\Backend\Access\User\ManageUserRequest::class
        );
    }

    // test cases...
}
