<?php

namespace Tests\Feature\Http\Controllers\Frontend\Auth;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Frontend\Auth\ChangePasswordController
 */
class ChangePasswordControllerTest extends TestCase
{
    /**
     * @test
     */
    public function change_password_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->patch(route('frontend.auth.password.change'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function changepassword_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Frontend\Auth\ChangePasswordController::class,
            'changePassword',
            \App\Http\Requests\Frontend\User\ChangePasswordRequest::class
        );
    }

    // test cases...
}
