<?php

namespace Tests\Feature\Http\Controllers\Frontend\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Frontend\Auth\ConfirmAccountController
 */
class ConfirmAccountControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function confirm_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.account.confirm', ['token' => $token]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function send_confirmation_email_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.account.confirm.resend', ['user' => $user]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
