<?php

namespace Tests\Feature\Http\Controllers\Frontend\Auth;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Frontend\Auth\RegisterController
 */
class RegisterControllerTest extends TestCase
{
    /**
     * @test
     */
    public function register_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('frontend.auth.register'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function register_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Frontend\Auth\RegisterController::class,
            'register',
            \App\Http\Requests\Frontend\Auth\RegisterRequest::class
        );
    }

    /**
     * @test
     */
    public function show_registration_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.register'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
