<?php

namespace Tests\Feature\Http\Controllers\Frontend\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Frontend\Auth\SocialLoginController
 */
class SocialLoginControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function login_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('frontend.auth.social.login', ['provider' => $provider]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
